[package]
name = "rust-design-way"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
once_cell = "1.9.0"
rand = "0.6"
chrono = "0.4.19"
timer = "0.2.0"

[dev-dependencies]
