[package]
name = "design-patterns-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
once_cell = "1.19.0"
rand = "0.8"
chrono = "0.4.34"
timer = "0.2.0"

[dev-dependencies]
