[package]
name = "design-patterns-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
once_cell = "1.13.1"
rand = "0.8"
chrono = "0.4.22"
timer = "0.2.0"

[dev-dependencies]
